/* Halloween Interactive World — flat GitHub build
   All media is referenced from the repository root so no asset folder is required. */
const state={view:'home',history:0,vocab:0,restaurant:0,quiz:0,quizSelected:null,quizRevealed:false,fastest:0,restaurantReveal:false,game:0,gameSelected:[],gameRevealed:false,experience:0,scenario:null,team:{name:'',members:'',roles:'',scenario:''},scores:Array(10).fill(0),session:null};
const historySlides=[
['Samhain','01_samhain.jpeg'],['Christianity and All Saints’ Day','02_christianity_and_all_saints_day.jpeg'],['Halloween – The Name','03_halloween_the_name.jpeg'],['Legend of Jack-o’-Lanterns','04_legend_of_jack_o_lanterns.jpeg'],['Pumpkins','05_pumpkins.jpeg'],['Halloween Celebrations','06_halloween_celebrations.jpeg'],['Trick or Treating','07_trick_or_treating.jpeg'],['Halloween Events','08_halloween_events.jpeg'],['Pumpkin Records','09_pumpkin_records.jpeg'],['2010 World Record Pumpkin Pie','10_2010_world_record_pumpkin_pie.jpeg'],['Most Lit Pumpkins','11_most_lit_pumpkins.jpeg'],['Fastest Pumpkin Carver','12_fastest_pumpkin_carver.jpeg']];
const vocab=[['Pumpkin','01_pumpkin.jpg'],['Jack-o’-lantern','02_jack_o_lantern.jpg'],['Candle','03_candle.jpg'],['Lantern','04_lantern.jpg'],['Broomstick','05_broomstick.jpg'],['Cauldron','06_cauldron.jpg'],['Magic wand','07_magic_wand.jpg'],['Potion','08_potion.jpg'],['Tombstone','09_tombstone.jpg'],['Coffin','10_coffin.jpg'],['Haunted house','11_haunted_house.jpg'],['Ghost','12_ghost.jpg'],['Witch','13_witch.jpg'],['Vampire','14_vampire.jpg'],['Zombie','15_zombie.jpg'],['Skeleton','16_skeleton.jpg'],['Mummy','17_mummy.jpg'],['Frankenstein Monster','19_frankenstein_monster.jpg'],['Devil','20_devil.jpg'],['Demon','21_demon.jpg'],['Bat','22_bat.jpg'],['Spider','23_spider.jpg'],['Spider web','24_spider_web.svg'],['Owl','25_owl.jpg'],['Raven','26_raven.jpg'],['Rat','27_rat.jpg'],['Wolf','28_wolf.jpg'],['Full moon','29_full_moon.jpg'],['Shadow','30_shadow.jpg'],['Bonfire','31_bonfire.jpg'],['Scarecrow','32_scarecrow.jpg'],['Skull','33_skull.jpg'],['Bones','34_bones.jpg'],['Witch hat','35_witch_hat.jpg'],['Mask','36_mask.jpg'],['Cape','37_cape.jpg'],['Fangs','38_fangs.jpg'],['Horns','39_horns.jpg'],['Claws','40_claws.jpg'],['Wings','41_wings.jpg'],['Tail','42_tail.jpg'],['Costume','43_costume.jpg'],['Caramel apple','44_caramel_apple.jpg'],['Candy corn','45_candy_corn.jpg'],['Sweets','46_sweets.jpg'],['Chocolate','47_chocolate.jpg'],['Lollipop','48_lollipop.jpg'],['Jelly beans','49_jelly_beans.jpg'],['Marshmallows','50_marshmallows.jpg'],['Brownie','51_brownie.jpg'],['Cake','52_cake.jpg'],['Popcorn','53_popcorn.jpg'],['Maze','53_maze.svg']];
const restaurant=[['Waiter','23_waiter.jpeg'],['Waitress','24_waitress.jpeg'],['Chef','37_chef.png'],['Customer','13_waiter_service.jpeg'],['Restaurant','08_restaurant.jpeg'],['Kitchen','38_kitchen.png'],['Bar','25_bar.jpeg'],['Dining room','18_dining_room.jpeg'],['Menu','39_menu.png'],['Plate','40_plate.png'],['Soup','14_pumpkin_soup.jpeg'],['Glass','41_glass.png'],['Knife','15_knife.jpeg'],['Fork','42_fork.png'],['Spoon','27_spoon.jpeg'],['Cutlery','43_cutlery.png'],['Cow','16_cow.jpeg'],['Beef','44_beef.png'],['Steak','17_beef_steak.jpeg'],['Fillet','28_steak.jpeg'],['Pig','01_pig.jpeg'],['Pork','45_pork.png'],['Sheep','46_sheep.png'],['Mutton','32_lamb.jpeg'],['Lamb','03_roast_lamb.jpeg'],['Lamb meat','03_roast_lamb.jpeg'],['Calf','19_calf.jpeg'],['Veal','29_meat_assortment.jpeg'],['Chicken','20_chicken.jpeg'],['Turkey','04_roast_turkey.jpeg'],['Duck','05_duck.jpeg'],['Raw','09_raw_steak.jpeg'],['Grilled','21_grilled.jpeg'],['Fried','33_fried.jpeg'],['Baked','47_baked.png'],['Roasted','22_roasted.jpeg'],['Boiled','10_boiled.jpeg'],['Steamed','06_steamed_dumplings.jpeg'],['Spicy','26_spicy.jpeg'],['Sweet','48_sweet.png'],['Salty','11_salty.jpeg'],['Vegetarian','02_vegan_salad.jpeg'],['Vegan','07_vegan_salad.jpeg'],['Gluten-free','49_gluten_free.png'],['Fish','35_fish.jpeg'],['Salmon','12_salmon.jpeg'],['Prawns','50_prawns.png'],['Mussels','30_mussels.jpeg'],['Squid','36_squid.jpeg'],['Octopus','51_octopus.png'],['Lobster','52_lobster.png'],['Crab','53_crab.png'],['Sauce','31_sauce.jpeg'],['Side dish','54_side_dish.png']];
const quiz=[
['What was Samhain?',['A medieval Halloween game','An ancient Celtic festival','A pumpkin competition','A Christian feast'],1],
['What does “Halloween” refer to historically?',['The evening before All Saints’ Day','The first day of winter','The pumpkin harvest','A Roman holiday'],0],
['What were jack-o’-lanterns traditionally carved from before pumpkins became common?',['Apples','Turnips','Potatoes','Corn'],1],
['Which vegetable became strongly associated with modern Halloween?',['Pumpkin','Carrot','Cucumber','Onion'],0],
['What does trick-or-treating involve?',['Lighting candles in churches','Visiting homes for treats','Carving only wooden masks','Watching fireworks'],1],
['Which celebration is connected with 1 November?',['All Saints’ Day','Samhain Eve','Pumpkin Day','Harvest Night'],0],
['Halloween is traditionally celebrated on which date?',['30 October','31 October','1 November','2 November'],1],
['Which activity is mentioned in the history presentation?',['Pumpkin carving','Ice skating','Beach racing','Snowboarding'],0],
['What do pumpkin records measure?',['Different pumpkin achievements','Weather forecasts','School grades','Restaurant prices'],0],
['What was the 2010 record connected with?',['A giant pumpkin pie','A haunted castle','A costume parade','A candle display'],0],
['What record involved many illuminated pumpkins?',['Most lit pumpkins','Fastest pumpkin meal','Largest costume','Longest parade'],0],
['Which skill appears in the final history slide?',['Fastest pumpkin carving','Fastest candy eating','Fastest costume sewing','Fastest ghost drawing'],0],
['Which event helped Halloween become a major celebration in the United States?',['Community celebrations','Winter sports','Spring festivals','Summer fairs'],0],
['What is a common Halloween symbol?',['A pumpkin','A sunflower','A snowflake','A seashell'],0],
['Which tradition is associated with children visiting homes?',['Trick-or-treating','Caroling at Easter','Maypole dancing','Bonfire racing'],0]
];
const situations=[
['Cooking method','The food is cooked in very hot oil until it becomes golden and crispy.',['Fried','Grilled','Raw','Baked','Boiled'],[0]],
['Dietary choice','The customer does not eat any animal products.',['Vegan','Vegetarian','Gluten-free','Sweet'],[0]],
['Flavour','The dish contains chilli and has a strong heat.',['Spicy','Sweet','Salty','Raw'],[0]],
['Cooking method','The food is cooked in an oven.',['Baked','Steamed','Fried','Raw'],[0]],
['Meal accompaniment','A smaller item served alongside the main course.',['Side dish','Dessert','Menu','Sauce'],[0]],
['Service equipment','Which items are used to eat a meal?',['Cutlery','Broomstick','Menu','Glass'],[0,3]],
['Seafood','Which options can be seafood?',['Prawns','Mussels','Chicken','Lobster'],[0,1,3]],
['Cooking methods','Which methods cook food without frying it?',['Grilled','Baked','Steamed','Raw'],[0,1,2]]];
const experience=[['Customer Arrives','The customer arrives at the restaurant. Welcome them warmly and politely.','08_restaurant.jpeg'],['Welcome','Greet the customer and offer a friendly welcome.','23_waiter.jpeg'],['Seating','Confirm the booking or party size and show the customer to the table.','18_dining_room.jpeg'],['Drinks','Offer drinks and explain the available options.','41_glass.png'],['Choosing Food','Give the menu and help the customer understand the choices.','39_menu.png'],['Taking the Order','Listen carefully and record the customer’s order.','23_waiter.jpeg'],['Confirming the Order','Repeat the order to make sure everything is correct.','13_waiter_service.jpeg'],['Serving','Bring the food and drinks professionally and politely.','22_roasted.jpeg'],['Checking the Meal','Check that the customer is happy with the food.','13_waiter_service.jpeg'],['Dessert & Coffee','Offer dessert and coffee and answer questions about the options.','48_sweet.png'],['Bill','Present the bill clearly and politely.','40_plate.png'],['Payment','Process the payment and thank the customer.','41_glass.png'],['Goodbye','Say goodbye warmly and invite the customer to return.','08_restaurant.jpeg']];
const scenarios=[['Romantic Couple','A couple celebrating a special occasion.','18_dining_room.jpeg'],['Family Birthday','A family with children celebrating a birthday.','08_restaurant.jpeg'],['Rude Vegan Customer','A difficult customer who complains about non-vegan options.','13_waiter_service.jpeg'],['Wrong Order','A customer receives the wrong dish and asks for a correction.','13_waiter_service.jpeg'],['Dietary Request','A guest asks about ingredients and dietary restrictions.','49_gluten_free.png'],['Birthday Surprise','The restaurant prepares a surprise celebration.','08_restaurant.jpeg'],['Busy Halloween Night','The restaurant is full and service must remain professional.','18_dining_room.jpeg'],['Special Celebration / Tourists','Tourists celebrate a special evening and need friendly assistance.','41_glass.png']];
const assessment=['Sequence','Restaurant vocabulary','Useful language','English accuracy','Interaction','Role performance','Customer service','Menu use','Creativity','Preparation & teamwork'];
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window._toast);window._toast=setTimeout(()=>t.classList.remove('show'),2400)}
function go(v){state.view=v;render();window.scrollTo({top:0,behavior:'smooth'})}
function shell(title,body,crumb='Halloween Interactive World'){document.getElementById('app').innerHTML=`<div class="app-bg"><div class="shell"><header class="top"><button class="brand" onclick="go('home')">🎃 <span>${crumb}</span></button><div class="top-actions"><button onclick="go('teacher')">Teacher Mode</button><button onclick="go('student')">Student Mode</button><button class="home-btn" onclick="go('home')">Home</button></div></header><main>${body}</main></div></div>`}
function titleBlock(kicker,title,sub=''){return `<div class="title-block"><span class="kicker">${kicker}</span><h1>${title}</h1>${sub?`<p>${sub}</p>`:''}</div>`}
function nav(prev,next){return `<div class="pager"><button class="gold-btn" onclick="${prev}">← Previous</button><div class="page-dots"></div><button class="gold-btn" onclick="${next}">Next →</button></div>`}
function home(){document.getElementById('app').innerHTML=`<div class="home"><img src="landing-background.jpg" alt="Halloween Interactive World" class="landing"><button class="hot h-teacher" onclick="go('teacher')" aria-label="Enter Teacher Mode"></button><button class="hot h-student" onclick="go('student')" aria-label="Join as a Student"></button>${[[1,'history','h1world'],[2,'quiz','h2world'],[3,'vocab','h3world'],[4,'fastest','h4world'],[5,'restaurant','h5world'],[6,'build','h6world'],[7,'experience','h7world'],[8,'scenarios','h8world']].map(x=>`<button class="hot ${x[2]}" onclick="go('${x[1]}')" aria-label="Open ${x[1]}"></button>`).join('')}</div>`}
function historyView(){const s=historySlides[state.history];shell('Halloween History',`${titleBlock('WORLD 1 • HISTORY',s[0],`Slide ${state.history+1} of ${historySlides.length}`)}<section class="history-slide"><img src="${s[1]}" alt="${esc(s[0])}"></section>${nav(`state.history=(state.history+${historySlides.length-1})%${historySlides.length};render()`,`state.history=(state.history+1)%${historySlides.length};render()`)}`,'Halloween History')}
function vocabView(){const v=vocab[state.vocab];shell('Vocabulary World',`${titleBlock('WORLD 3 • VOCABULARY','📚 Halloween Vocabulary World',`Picture → Guess → Reveal Word • ${state.vocab+1} of ${vocab.length}`)}<section class="teaching-card"><div class="image-frame"><img src="${v[1]}" alt="${esc(v[0])}"></div><div class="parchment"><span class="question-label">What is this?</span><div class="word-reveal">${state.vocabReveal?esc(v[0]):'?'}</div><p>Let students look, guess and say the English word before revealing it.</p><button class="gold-btn" onclick="state.vocabReveal=!state.vocabReveal;render()">${state.vocabReveal?'Hide Word':'Reveal Word'}</button></div></section>${nav(`state.vocab=(state.vocab+${vocab.length-1})%${vocab.length};state.vocabReveal=false;render()`,`state.vocab=(state.vocab+1)%${vocab.length};state.vocabReveal=false;render()`)}`,'Vocabulary World')}
function quizView(){const q=quiz[state.quiz];shell('Spooky Quiz',`${titleBlock('WORLD 2 • SPOOKY QUIZ','👻 Spooky Quiz',`Question ${state.quiz+1} of ${quiz.length} • 30 seconds minimum per question`)}<section class="quiz-layout"><aside class="game-panel"><h3>Game Code</h3><div class="code">${state.session||'X7K9'}</div><p>Students join with their own name and this session code.</p><button class="small-btn" onclick="newSession()">New Session</button></aside><div class="question-card"><div class="timer">00:30</div><h2>${esc(q[0])}</h2><div class="answers">${q[1].map((a,i)=>`<button class="answer ${state.quizSelected===i?'selected':''} ${state.quizRevealed&&i===q[2]?'correct':''} ${state.quizRevealed&&state.quizSelected===i&&i!==q[2]?'wrong':''}" onclick="state.quizSelected=${i};render()"><b>${String.fromCharCode(65+i)}</b> ${esc(a)}</button>`).join('')}</div><div class="quiz-controls"><button class="gold-btn" onclick="state.quizRevealed=true;render()">Reveal Correct Answer</button><button class="purple-btn" onclick="go('podium')">Show Results</button></div></div><aside class="game-panel"><h3>Teacher Control</h3><p>Show question → students submit → reveal → results → leaderboard → next.</p><div class="leader-mini"><b>Leaderboard</b><span>Emma · 90</span><span>Liam · 80</span><span>Noah · 70</span></div></aside></section>${nav(`state.quiz=(state.quiz+${quiz.length-1})%${quiz.length};state.quizSelected=null;state.quizRevealed=false;render()`,`state.quiz=(state.quiz+1)%${quiz.length};state.quizSelected=null;state.quizRevealed=false;render()`)}`,'Spooky Quiz')}
function podiumView(){shell('Quiz Results',`${titleBlock('QUIZ RESULTS • PODIUM','🏆 Quiz Champion!','Final results presentation') }<section class="podium"><div class="pod third"><span>🥉</span><h3>Liam</h3><b>80 points</b></div><div class="pod first"><span>🏆</span><h2>Emma</h2><b>90 points</b></div><div class="pod second"><span>🥈</span><h3>Noah</h3><b>70 points</b></div></section><div class="center-actions"><button class="purple-btn" onclick="toast('Full leaderboard opened.')">View Full Leaderboard</button><button class="gold-btn" onclick="state.quiz=0;state.quizSelected=null;state.quizRevealed=false;go('quiz')">Play Again</button></div>`,'Spooky Quiz')}
function fastestView(){shell('Fastest Finger First',`${titleBlock('WORLD 4 • SPEED GAME','⚡ Fastest Finger First',`Game Code ${state.session||'X7K9'} • Tap your phone to answer first`)}<section class="fast-layout"><aside class="game-panel"><h3>Game Code</h3><div class="code">${state.session||'X7K9'}</div><h3>Participants (8)</h3>${['Aisha','Daniel','Maria','Lucas','Priya','Ethan','Sophie','Omar'].map((n,i)=>`<div class="person"><i>${i+1}</i>${n}<span>${i<4?'●':''}</span></div>`).join('')}</aside><div class="fast-main"><div class="fast-image"><img src="${vocab[state.fastest%vocab.length][1]}" alt="${vocab[state.fastest%vocab.length][0]}"></div><h2>Who knows this word?</h2><div class="waiting">🟨 Waiting for the fastest finger…</div></div><aside class="game-panel"><h3>Answer Order</h3>${['Aisha','Daniel','Maria','Lucas'].map((n,i)=>`<div class="person"><i>${i+1}</i>${n}<span>${(2.1+i*.7).toFixed(1)}s</span></div>`).join('')}<button class="correct-btn" onclick="toast('Correct — +10 points')">Correct<br><small>(+10 points)</small></button><button class="wrong-btn" onclick="state.fastest=(state.fastest+1)%${vocab.length};render()">Wrong<br><small>(Next student)</small></button></aside></section>${nav(`state.fastest=(state.fastest+${vocab.length-1})%${vocab.length};render()`,`state.fastest=(state.fastest+1)%${vocab.length};render()`)}`,'Fastest Finger First')}
function restaurantView(){const r=restaurant[state.restaurant];shell('Restaurant World',`${titleBlock('WORLD 5 • RESTAURANT VOCABULARY','🍽️ Restaurant World',`Picture → Guess → Reveal Word • ${state.restaurant+1} of ${restaurant.length}`)}<section class="teaching-card"><div class="image-frame"><img src="${r[1]}" alt="${esc(r[0])}"></div><div class="parchment"><span class="question-label">What is this?</span><div class="word-reveal">${state.restaurantReveal?esc(r[0]):'?'}</div><p>Use the picture to teach restaurant English before revealing the term.</p><button class="gold-btn" onclick="state.restaurantReveal=!state.restaurantReveal;render()">${state.restaurantReveal?'Hide Word':'Reveal Word'}</button></div></section>${nav(`state.restaurant=(state.restaurant+${restaurant.length-1})%${restaurant.length};state.restaurantReveal=false;render()`,`state.restaurant=(state.restaurant+1)%${restaurant.length};state.restaurantReveal=false;render()`)}`,'Restaurant World')}
function restaurantGame(){const s=situations[state.game];shell('Restaurant Game',`${titleBlock('WORLD 6 • RESTAURANT GAME','🎯 Restaurant Game','Read the situation and select ALL applicable answers. The number of correct answers is not shown.') }<section class="situation"><div class="game-panel"><span class="kicker">${s[0]}</span><h2>${s[1]}</h2><p>Any number can be correct. Select every answer that applies, then submit.</p></div><div class="multi-grid">${s[2].map((a,i)=>`<button class="multi ${state.gameSelected.includes(i)?'picked':''} ${state.gameRevealed&&s[3].includes(i)?'right':''} ${state.gameRevealed&&state.gameSelected.includes(i)&&!s[3].includes(i)?'bad':''}" onclick="toggleGame(${i})">${esc(a)}</button>`).join('')}</div><div class="center-actions"><button class="gold-btn" onclick="state.gameRevealed=true;render()">${state.gameRevealed?'Answers Revealed':'Submit & Reveal'}</button></div></section>${nav(`state.game=(state.game+situations.length-1)%situations.length;state.gameSelected=[];state.gameRevealed=false;render()`,`state.game=(state.game+1)%situations.length;state.gameSelected=[];state.gameRevealed=false;render()`)}`,'Restaurant Game')}
function toggleGame(i){state.gameSelected=state.gameSelected.includes(i)?state.gameSelected.filter(x=>x!==i):[...state.gameSelected,i];render()}
function buildView(){shell('Build Your Own Restaurant',`${titleBlock('WORLD 7 • CREATION','👨‍🍳 Build Your Own Restaurant','Create the restaurant, menu and service identity that your team will use in role-play.') }<section class="form-grid"><label>Restaurant name<input placeholder="The Haunted Lantern"></label><label>Theme / concept<input placeholder="Gothic Halloween dining"></label><label>Starters<textarea placeholder="Starter 1\nStarter 2"></textarea></label><label>Main courses<textarea placeholder="Main course 1\nMain course 2"></textarea></label><label>Side dishes<textarea placeholder="Side dish 1\nSide dish 2"></textarea></label><label>Desserts & drinks<textarea placeholder="Dessert / drink"></textarea></label><label>Ingredients & cooking methods<textarea placeholder="Beef • grilled • sauce…"></textarea></label><label>Dietary / special options<textarea placeholder="Vegetarian • vegan • gluten-free • spicy/non-spicy"></textarea></label><label>Prices & Halloween identity<textarea placeholder="Prices, themed names, decorations, special offers/events…"></textarea></label><label>Service roles<textarea placeholder="Waiter • chef • customer • manager"></textarea></label></section><div class="center-actions"><button class="gold-btn" onclick="toast('Restaurant draft saved in this browser.')">Save Restaurant</button><button class="purple-btn" onclick="go('experience')">Continue to Complete Experience</button></div>`,'Build Your Own Restaurant')}
function experienceView(){const e=experience[state.experience];shell('Complete Restaurant Experience',`${titleBlock('WORLD 7 • SERVICE SEQUENCE','🍽️ Complete Restaurant Experience',`Step ${state.experience+1} of ${experience.length} • From arrival to goodbye`)}<section class="experience-card"><div class="exp-image"><img src="${e[2]}" alt="${esc(e[0])}"></div><div class="parchment"><h2>${esc(e[0])}</h2><p>${esc(e[1])}</p><div class="language-box"><b>Useful language</b><br>Welcome the customer politely, clarify details, confirm the order and close the service professionally.</div></div></section><div class="step-strip">${experience.map((x,i)=>`<button class="step ${i===state.experience?'active':''}" onclick="state.experience=${i};render()">${i+1}</button>`).join('')}</div>${nav(`state.experience=(state.experience+${experience.length-1})%${experience.length};render()`,`state.experience=(state.experience+1)%${experience.length};render()`)}`,'Complete Restaurant Experience')}
function scenariosView(){shell('Restaurant Scenarios',`${titleBlock('WORLD 8 • SCENARIOS','🎭 Restaurant Scenarios','Choose a situation for your team to prepare and perform.') }<section class="scenario-grid">${scenarios.map((s,i)=>`<article class="scenario"><img src="${s[2]}" alt="${esc(s[0])}"><div><h3>${esc(s[0])}</h3><p>${esc(s[1])}</p><button class="select-btn" onclick="state.scenario=${i};state.team.scenario=${i};go('team')">Select</button></div></article>`).join('')}</section>`,'Restaurant Scenarios')}
function teamView(){const s=scenarios[state.scenario??0];shell('Team Registration',`${titleBlock('TEAM REGISTRATION','👥 Team Registration',`Selected scenario: ${s[0]}`)}<section class="form-grid"><label>Team name<input value="${esc(state.team.name)}" oninput="state.team.name=this.value" placeholder="Team name"></label><label>Number of members<input value="${esc(state.team.members)}" oninput="state.team.members=this.value" type="number" min="1"></label><label>Member names<textarea oninput="state.team.names=this.value" placeholder="One name per line"></textarea></label><label>Roles<textarea oninput="state.team.roles=this.value" placeholder="Customer / Waiter / Chef / Manager…"></textarea></label></section><div class="center-actions"><button class="gold-btn" onclick="toast('Team saved for this browser session.')">Save Team</button><button class="purple-btn" onclick="go('assessment')">Final Assessment</button></div>`,'Team Registration')}
function assessmentView(){const total=state.scores.reduce((a,b)=>a+Number(b||0),0);shell('Final Assessment',`${titleBlock('FINAL ASSESSMENT','🏆 Team Assessment & Leaderboard','10 categories • 0–10 points each • Total 100') }<section class="assessment">${assessment.map((x,i)=>`<label><span>${i+1}. ${x}</span><input type="number" min="0" max="10" value="${state.scores[i]}" oninput="state.scores[${i}]=Math.max(0,Math.min(10,Number(this.value)||0));document.getElementById('totalScore').textContent=state.scores.reduce((a,b)=>a+Number(b||0),0)+' / 100'"></label>`).join('')}</section><div class="total-score" id="totalScore">${total} / 100</div><div class="center-actions"><button class="gold-btn" onclick="toast('Assessment saved.')">Save Assessment</button><button class="purple-btn" onclick="go('leaderboard')">Show Leaderboard</button></div>`,'Final Assessment')}
function leaderboard(){shell('Final Leaderboard',`${titleBlock('RESULTS','🏆 Final Leaderboard','Teacher-controlled team results') }<section class="leaderboard"><div class="rank r2"><b>2</b><h3>Team Shadow</h3><span>86 / 100</span></div><div class="rank r1"><b>1</b><h2>${esc(state.team.name||'Team Pumpkin')}</h2><span>${state.scores.reduce((a,b)=>a+Number(b||0),0)} / 100</span></div><div class="rank r3"><b>3</b><h3>Team Raven</h3><span>79 / 100</span></div></section>`,'Final Assessment')}
function teacher(){shell('Teacher Mode',`${titleBlock('PLAN • CONTROL • ASSESS','🧙 Teacher Mode','Each interactive activity starts with its own classroom session code.') }<section class="mode-grid">${[['quiz','👻 Spooky Quiz','History quiz with timer, reveal, results and podium.'],['fastest','⚡ Fastest Finger First','Students tap their phones to race to the answer.'],['restaurant-game','🎯 Restaurant Game','Select all correct restaurant vocabulary answers.'],['team','👥 Team Registration','Record teams, members, roles and scenarios.'],['assessment','🏆 Final Assessment','Score the complete role-play and produce results.']].map(x=>`<article><h3>${x[1]}</h3><p>${x[2]}</p><button class="gold-btn" onclick="${x[0]==='team'?'go(\'scenarios\')':x[0]==='assessment'?'go(\'assessment\')':`newSession();go('${x[0]}')`}">Open</button></article>`).join('')}</section><div class="teacher-note">Session isolation is represented in this GitHub-ready front end with a fresh code per activity. A true multi-device live classroom requires a realtime backend service.</div>`,'Teacher Mode')}
function student(){shell('Student Mode',`${titleBlock('JOIN • PARTICIPATE • HAVE FUN','🧟 Student Mode','Enter the teacher’s current session code and your name.') }<section class="join-card"><label>Session code<input id="joinCode" placeholder="X7K9" maxlength="8"></label><label>Your name<input id="joinName" placeholder="Your name"></label><button class="purple-btn" onclick="join()">Join Session</button></section>`,'Student Mode')}
function newSession(){state.session=Math.random().toString(36).slice(2,6).toUpperCase();toast('New classroom session: '+state.session)}
function join(){const c=(document.getElementById('joinCode').value||'').trim().toUpperCase(),n=(document.getElementById('joinName').value||'').trim();if(!c||!n)return toast('Enter the session code and your name.');toast(`${n} joined session ${c}.`)}
function render(){if(state.view==='home')return home();if(state.view==='history')return historyView();if(state.view==='vocab')return vocabView();if(state.view==='quiz')return quizView();if(state.view==='podium')return podiumView();if(state.view==='fastest')return fastestView();if(state.view==='restaurant')return restaurantView();if(state.view==='restaurant-game')return restaurantGame();if(state.view==='build')return buildView();if(state.view==='experience')return experienceView();if(state.view==='scenarios')return scenariosView();if(state.view==='team')return teamView();if(state.view==='assessment')return assessmentView();if(state.view==='leaderboard')return leaderboard();if(state.view==='teacher')return teacher();if(state.view==='student')return student();home()}
state.vocabReveal=false;state.restaurantReveal=false;render();
